print("VisualGuide")
print("Accessibility-focused visual enhancement tool")
print()
print("To use VisualGuide, please download the official installer:")
print("https://www.fnbubbles420.org/Visual-Guide/visual-guide-info")
print("VISUALGUIDE IS STILL UNDER CONSTRUCTION")
